version: '3.8'
services:
    postgres:
        image: postgres:14.5
        restart: always
        user: postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 4s
            timeout: 4s
            retries: 5
        stdin_open: true
        tty: true

    backend-user:
        build:
            dockerfile: dockerfiles/Dockerfile.dev
            context: .
            args:
                - NPM_TOKEN=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
        environment:
            - ENVIRONMENT=dev
            - REFRESH_TOKEN_PAYLOAD_SECRET=my-super-secret3
            - PORT=6300
        volumes:
            - /app/node_modules
            - .:/app
        ports:
            - 6300:6300
        depends_on:
            postgres:
                condition: service_healthy
