version: '3.8'
services:
    postgres:
        image: postgres:14.5
        restart: always
        user: postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - database
        stdin_open: true
        tty: true

    backend-user:
        build:
            dockerfile: dockerfiles/Dockerfile.dev
            context: .
        environment:
            - ENVIRONMENT=dev
            - PORT=49202
        volumes:
            - /app/node_modules
            - .:/app
        ports:
            - '49202:49202'
        networks:
            - database
        depends_on:
            postgres:
                condition: service_healthy

networks:
    database:
        driver: bridge
